<script>
 import {onMount} from 'svelte';import {language} from '$lib/language.js';import T from '$lib/T.svelte';import Meta from '$lib/Meta.svelte';import GuideHeader from '$lib/GuideHeader.svelte';
 const groups=[['Документы и деньги','Hujjatlar va pul',[
 ['passport','Загранпаспорт и копии документов','Xorijga chiqish pasporti va hujjat nusxalari'],['tickets','Билеты, бронь отеля и адрес проживания офлайн','Chiptalar, mehmonxona broni va manzilning oflayn nusxasi'],['insurance','Страховой полис и телефон помощи','Sug‘urta polisi va yordam telefoni'],['money','Банковская карта и небольшой запас наличных','Bank kartasi va ozroq naqd pul']]],
 ['В ручную кладь','Qo‘l yukiga',[
 ['phone','Телефон, зарядка и подходящий адаптер','Telefon, quvvatlagich va mos adapter'],['essentials','Необходимые личные средства и лекарства в оригинальной упаковке','Zarur shaxsiy vositalar va dorilar asl qadoqda'],['layer','Лёгкая кофта и вещи на случай задержки багажа','Yengil kofta va yuk kechikishi uchun kerakli kiyim'],['contacts','Контакты менеджера, отеля и близких','Menejer, mehmonxona va yaqinlar kontaktlari']]],
 ['Одежда и отдых','Kiyim va dam olish',[
 ['shoes','Удобная обувь для прогулок','Sayr uchun qulay poyabzal'],['weather','Одежда по прогнозу погоды и лёгкий дождевик','Ob-havoga mos kiyim va yengil yomg‘irpo‘sh'],['sun','Головной убор, очки и солнцезащитное средство','Bosh kiyim, ko‘zoynak va quyoshdan himoya vositasi'],['beach','Купальные вещи для пляжной поездки','Plyaj safariga cho‘milish kiyimlari']]]];
 const ids=groups.flatMap(g=>g[2].map(i=>i[0]));let checked=$state([]);let ready=$state(false);
 onMount(()=>{try{const saved=JSON.parse(localStorage.getItem('mandarin-packing')||'[]');if(Array.isArray(saved))checked=saved.filter(x=>ids.includes(x));}catch{}ready=true;});
 $effect(()=>{if(ready)try{localStorage.setItem('mandarin-packing',JSON.stringify(checked));}catch{}});
</script>
<Meta ru="Что взять в поездку" uz="Safarga nimalar olish kerak"/>
<GuideHeader ru="Чемодан без лишней суеты." uz="Chamadonni ortiqcha tashvishsiz yig‘ing." introRu="Отмечайте готовое. Список сохраняется в этом браузере — можно вернуться позже." introUz="Tayyor narsalarni belgilang. Ro‘yxat shu brauzerda saqlanadi — keyinroq qaytishingiz mumkin."/>
<section class="wrap guide-content"><div class="packing-progress"><p role="status"><T ru="Собрано" uz="Yig‘ildi"/> {checked.length} / {ids.length}</p><button type="button" class="reset-checklist" onclick={()=>checked=[]}><T ru="Сбросить отметки" uz="Belgilarni tozalash"/></button></div><progress value={checked.length} max={ids.length} aria-label={$language==='ru'?'Прогресс сборов':'Tayyorgarlik jarayoni'}></progress><div class="guide-grid">{#each groups as [ru,uz,items]}<article class="guide-panel"><h2><T {ru} {uz}/></h2>{#each items as [id,r,u]}<label class:packed={checked.includes(id)} class="packing-item"><input type="checkbox" value={id} bind:group={checked}/><span><T ru={r} uz={u}/></span></label>{/each}</article>{/each}</div><p class="guide-note"><T ru="Размеры багажа, жидкости, аккумуляторы и правила ввоза лекарств проверьте у авиакомпании и страны назначения. Универсальных норм для всех поездок нет." uz="Yuk o‘lchami, suyuqliklar, akkumulyatorlar va dorilarni olib kirish qoidalarini aviakompaniya hamda boradigan mamlakatdan tekshiring. Barcha safarlar uchun yagona me’yor yo‘q."/></p></section>
