<script>
 import T from '$lib/T.svelte';import Meta from '$lib/Meta.svelte';import GuideHeader from '$lib/GuideHeader.svelte';import Icon from '$lib/Icon.svelte';
 const mfa='https://gov.uz/oz/mfa/pages/o-zbekiston-respublikasi-fuqarolari-uchun-viza-talablari';
 const countries=[
 ['🇹🇷','Турция','Turkiya','До 90 дней в течение 180 дней','180 kun ichida 90 kungacha','https://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa','МИД Турции','Turkiya TIV','turkey'],
 ['🇲🇾','Малайзия','Malayziya','До одного месяца','Bir oygacha','https://www.kln.gov.my/documents/33464/271043/IMMIGRATION%2B-%2BVISA%2BREQUIREMENT%2BFOR%2BFOREIGNERS%2BTRAVELLING%2BTO%2BMALAYSIA/fda53f77-f949-44f6-9289-a08511d57838?download=true&version=1.3','МИД Малайзии (PDF)','Malayziya TIV (PDF)','malaysia'],
 ['🇰🇿','Казахстан','Qozog‘iston','До 90 дней по таблице МИД Казахстана','Qozog‘iston TIV jadvali bo‘yicha 90 kungacha','https://www.gov.kz/memleket/entities/mfa/activities/34747?lang=en','МИД Казахстана','Qozog‘iston TIV','kazakhstan'],
 ['🇬🇪','Грузия','Gruziya','Безвизовый режим; срок уточните перед поездкой','Vizasiz tartib; muddatni safardan oldin aniqlang',mfa,'МИД Узбекистана','O‘zbekiston TIV','georgia'],
 ['🇦🇪','ОАЭ','BAA','Безвизовый режим; срок уточните перед поездкой','Vizasiz tartib; muddatni safardan oldin aniqlang',mfa,'МИД Узбекистана','O‘zbekiston TIV','dubai'],
 ['🇹🇭','Таиланд','Tailand','Безвизовый режим; срок уточните перед поездкой','Vizasiz tartib; muddatni safardan oldin aniqlang',mfa,'МИД Узбекистана','O‘zbekiston TIV',null]
 ];
</script>
<Meta ru="Безвизовые направления для граждан Узбекистана" uz="O‘zbekiston fuqarolari uchun vizasiz yo‘nalishlar"/>
<GuideHeader ru="Больше путешествий. Меньше формальностей." uz="Ko‘proq sayohat. Kamroq rasmiyatchilik." introRu="Подборка безвизовых направлений для граждан Узбекистана с обычным заграничным паспортом. Для коротких туристических поездок." introUz="Oddiy xorijga chiqish pasportiga ega O‘zbekiston fuqarolari uchun qisqa turistik safarlarga vizasiz yo‘nalishlar."/>
<section class="wrap guide-content"><p class="guide-note"><T ru="Проверено 16 сентября 2026 года. Правила могут измениться. До оплаты сверьте срок пребывания, срок действия паспорта, регистрацию и дополнительные условия у консульства страны. Безвизовый режим не гарантирует въезд и не даёт права работать." uz="2026-yil 16-sentabrda tekshirildi. Qoidalar o‘zgarishi mumkin. To‘lovdan oldin qolish muddati, pasport amal qilishi, ro‘yxatdan o‘tish va qo‘shimcha shartlarni mamlakat konsulligidan tekshiring. Vizasiz tartib kirishni kafolatlamaydi va ishlash huquqini bermaydi."/></p>
<div class="guide-grid">{#each countries as [flag,r,u,dr,du,url,sr,su,slug]}<article class="guide-panel visa-panel"><span class="country-flag" aria-hidden="true">{flag}</span><div class="eyebrow"><T ru="Без визы" uz="Vizasiz"/></div><h2><T ru={r} uz={u}/></h2><p><T ru={dr} uz={du}/></p><a class="guide-source" href={url} target="_blank" rel="noopener"><T ru={sr} uz={su}/> <Icon name="external"/></a>{#if slug}<a class="text-link" href={'/tours/'+slug+'/'}><T ru="Об этом направлении" uz="Yo‘nalish haqida"/> <Icon/></a>{/if}</article>{/each}</div>
<div class="guide-panel visa-explainer"><h2><T ru="Без визы, eVisa и виза по прилёте — в чём разница?" uz="Vizasiz, eVisa va kelganda viza — farqi nimada?"/></h2><p><T ru="Безвизовый режим позволяет путешествовать без визы при соблюдении условий въезда. Электронную визу обычно оформляют до поездки. Виза по прилёте — отдельная процедура на границе, которая может требовать оплаты и документов. Эти режимы не взаимозаменяемы." uz="Vizasiz tartib kirish shartlariga rioya qilib vizasiz safar qilish imkonini beradi. Elektron viza odatda safardan oldin rasmiylashtiriladi. Kelganda viza chegaradagi alohida jarayon bo‘lib, to‘lov va hujjatlar talab qilinishi mumkin. Bu tartiblar bir xil emas."/></p><a class="guide-source" href={mfa} target="_blank" rel="noopener"><T ru="Полный перечень МИД Узбекистана" uz="O‘zbekiston TIV to‘liq ro‘yxati"/> <Icon name="external"/></a></div></section>
